default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: feed_alerts_development

test:
  <<: *default
  database: feed_alerts_test

production:
  url: <%= ENV['DATABASE_URL'] %>
